<?php
/**
 * BuildHub Maker - Conflict Guard
 * Auto-generated by BuildHub Maker. Do not edit.
 */
if ( ! defined( 'ABSPATH' ) ) exit;

add_filter( 'option_active_plugins', function( $plugins ) {
    if ( ! is_array( $plugins ) ) return $plugins;

    $bh_free = 'buildhub-maker/buildhub-maker.php';
    $bh_pro  = 'buildhub-maker-pro/buildhub-maker.php';
    $bh_dev  = 'buildhub-maker-dev/buildhub-maker.php';

    $has_free = in_array( $bh_free, $plugins, true );
    $has_pro  = in_array( $bh_pro,  $plugins, true );
    $has_dev  = in_array( $bh_dev,  $plugins, true );

    $count = (int) $has_free + (int) $has_pro + (int) $has_dev;
    if ( $count <= 1 ) return $plugins;

    $winner = get_option( 'bh_active_variant', 'free' );

    if ( $winner === 'pro' && $has_pro ) {
        $remove = [ $bh_free, $bh_dev ];
    } elseif ( $winner === 'dev' && $has_dev ) {
        $remove = [ $bh_free, $bh_pro ];
    } else {
        $remove = [ $bh_pro, $bh_dev ];
    }

    $new_plugins = array_values( array_diff( $plugins, $remove ) );

    // DB aktualisieren
    global $wpdb;
    $wpdb->update( // phpcs:ignore WordPress.DB.DirectDatabaseQuery
        $wpdb->options,
        [ 'option_value' => maybe_serialize( $new_plugins ) ],
        [ 'option_name'  => 'active_plugins' ]
    );
    wp_cache_delete( 'active_plugins', 'options' );

    // Verlierer-Ordner physisch löschen
    foreach ( $remove as $loser_basename ) {
        $loser_dir = WP_PLUGIN_DIR . '/' . dirname( $loser_basename );
        if ( is_dir( $loser_dir ) ) {
            // Rekursiv löschen
            $files = new RecursiveIteratorIterator(
                new RecursiveDirectoryIterator( $loser_dir, RecursiveDirectoryIterator::SKIP_DOTS ),
                RecursiveIteratorIterator::CHILD_FIRST
            );
            foreach ( $files as $f ) {
                $f->isDir() ? rmdir( $f->getRealPath() ) : unlink( $f->getRealPath() ); // phpcs:ignore WordPress.WP.AlternativeFunctions
            }
            rmdir( $loser_dir ); // phpcs:ignore WordPress.WP.AlternativeFunctions
        }
    }

    return $new_plugins;
}, 0 );
