<?php
/**
 * PROJECT-MANAGER v1.0 (CRUD for maker-config.php)
 * Path: /buildhub-maker/admin/project-manager.php
 */

if ( ! defined( 'ABSPATH' ) ) exit;

// We load the existing config to get the current $bh_projects array
if ( file_exists( BH_MAKER_PATH . 'maker-config.php' ) ) {
    include BH_MAKER_PATH . 'maker-config.php';
}

$status_msg = '';

/**
 * LOGIK: SPEICHERN DER DATEI
 */
if ( isset($_POST['bh_save_projects']) && check_admin_referer('bh_maker_crud_action') ) {
    $new_projects = $_POST['projects'];
    
    // Wir bauen den Dateiinhalt manuell auf, um die Struktur der maker-config zu erhalten
    $content = "<?php\n/**\n * MAKER-CONFIG (Auto-Generated by Project Manager)\n */\n\n";
    $content .= "if ( ! defined( 'ABSPATH' ) ) exit;\n\n";
    $content .= "if ( ! defined( 'BH_DEFAULT_PROJECT' ) ) {\n    define('BH_DEFAULT_PROJECT', '" . sanitize_text_field($_POST['default_project']) . "');\n}\n\n";
    
    $content .= "\$bh_projects = [\n";
    foreach ($new_projects as $key => $p) {
        $key = sanitize_key($key);
        $content .= "    '$key' => [\n";
        $content .= "        'FS_ID'         => '" . sanitize_text_field($p['FS_ID']) . "',\n";
        $content .= "        'FS_TOKEN'      => '" . sanitize_text_field($p['FS_TOKEN']) . "',\n";
        $content .= "        'GH_REPO'       => '" . sanitize_text_field($p['GH_REPO']) . "',\n";
        $content .= "        'PLUGIN_DOMAIN' => '" . sanitize_text_field($p['PLUGIN_DOMAIN']) . "',\n";
        $content .= "        'PLUGIN_NAME'   => '" . sanitize_text_field($p['PLUGIN_NAME']) . "',\n";
        $content .= "        'PLUGIN_AUTHOR' => '" . sanitize_text_field($p['PLUGIN_AUTHOR']) . "',\n";
        $content .= "        'PLUGIN_URI'    => '" . esc_url_raw($p['PLUGIN_URI']) . "',\n";
        $content .= "        'HAS_FREE'      => " . (isset($p['HAS_FREE']) ? 'true' : 'false') . ",\n";
        $content .= "    ],\n";
    }
    $content .= "];\n\n";
    
    // Shared Credentials Teil (Statisch aus bestehenden Konstanten oder Default)
    $content .= "if ( ! defined( 'GH_TOKEN' ) ) define('GH_TOKEN', '" . GH_TOKEN . "');\n";
    $content .= "if ( ! defined( 'MAIL_HOST' ) ) define('MAIL_HOST', '" . MAIL_HOST . "');\n";
    $content .= "if ( ! defined( 'MAIL_PORT' ) ) define('MAIL_PORT', " . MAIL_PORT . ");\n";
    $content .= "if ( ! defined( 'MAIL_USER' ) ) define('MAIL_USER', '" . MAIL_USER . "');\n";
    $content .= "if ( ! defined( 'MAIL_PASS' ) ) define('MAIL_PASS', '" . MAIL_PASS . "');\n\n";
    
    // Dynamic Logic (Fixed Block)
    $content .= "add_action( 'phpmailer_init', function( \$phpmailer ) {\n";
    $content .= "    \$phpmailer->isSMTP(); \$phpmailer->Host = MAIL_HOST; \$phpmailer->SMTPAuth = true; \$phpmailer->Port = MAIL_PORT;\n";
    $content .= "    \$phpmailer->Username = MAIL_USER; \$phpmailer->Password = MAIL_PASS; \$phpmailer->SMTPSecure = 'tls';\n";
    $content .= "    \$phpmailer->From = MAIL_USER; \$phpmailer->FromName = 'BuildHub Maker';\n});\n\n";
    
    $content .= "\$active_key = (isset(\$_REQUEST['bh_project'])) ? sanitize_text_field(\$_REQUEST['bh_project']) : BH_DEFAULT_PROJECT;\n";
    $content .= "if ( ! isset(\$bh_projects[\$active_key]) ) \$active_key = BH_DEFAULT_PROJECT;\n";
    $content .= "\$active = \$bh_projects[\$active_key];\n\n";
    $content .= "if ( ! defined( 'ACTIVE_PROJECT_KEY' ) ) define('ACTIVE_PROJECT_KEY', \$active_key);\n";
    $content .= "if ( ! defined( 'FS_ID' ) ) define('FS_ID', \$active['FS_ID']);\n";
    $content .= "if ( ! defined( 'FS_BEARER_TOKEN' ) ) define('FS_BEARER_TOKEN', \$active['FS_TOKEN']);\n";
    $content .= "foreach(['GH_REPO','PLUGIN_DOMAIN','PLUGIN_NAME','PLUGIN_AUTHOR','PLUGIN_URI','HAS_FREE'] as \$k) {\n";
    $content .= "    if ( ! defined(\$k) ) define(\$k, \$active[\$k]);\n}\n";

    if ( file_put_contents( BH_MAKER_PATH . 'maker-config.php', $content ) ) {
        $status_msg = '<div class="notice notice-success"><p>maker-config.php erfolgreich aktualisiert!</p></div>';
        // Reload array for UI
        include BH_MAKER_PATH . 'maker-config.php';
    }
}
?>

<div class="wrap">
    <h1>Project Manager (maker-config.php)</h1>
    <?php echo $status_msg; ?>
    
    <form method="post">
        <?php wp_nonce_field('bh_maker_crud_action'); ?>
        
        <table class="wp-list-table widefat fixed striped" style="margin-top:20px;">
            <thead>
                <tr>
                    <th>Key (Slug)</th>
                    <th>FS ID & Token</th>
                    <th>GitHub Repo</th>
                    <th>Plugin Meta</th>
                    <th>Options</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody id="bh-project-list">
                <?php foreach ($bh_projects as $slug => $p): ?>
                <tr class="project-row">
                    <td>
                        <input type="text" name="projects[<?php echo $slug; ?>][KEY]" value="<?php echo $slug; ?>" readonly style="background:#eee;">
                        <br><small>Default: <input type="radio" name="default_project" value="<?php echo $slug; ?>" <?php checked(BH_DEFAULT_PROJECT, $slug); ?>></small>
                    </td>
                    <td>
                        ID: <input type="text" name="projects[<?php echo $slug; ?>][FS_ID]" value="<?php echo $p['FS_ID']; ?>" style="width:100%;"><br>
                        Token: <input type="text" name="projects[<?php echo $slug; ?>][FS_TOKEN]" value="<?php echo $p['FS_TOKEN']; ?>" style="width:100%;">
                    </td>
                    <td><input type="text" name="projects[<?php echo $slug; ?>][GH_REPO]" value="<?php echo $p['GH_REPO']; ?>" style="width:100%;"></td>
                    <td>
                        Name: <input type="text" name="projects[<?php echo $slug; ?>][PLUGIN_NAME]" value="<?php echo $p['PLUGIN_NAME']; ?>" style="width:100%;"><br>
                        Domain: <input type="text" name="projects[<?php echo $slug; ?>][PLUGIN_DOMAIN]" value="<?php echo $p['PLUGIN_DOMAIN']; ?>" style="width:100%;">
                    </td>
                    <td>
                        Author: <input type="text" name="projects[<?php echo $slug; ?>][PLUGIN_AUTHOR]" value="<?php echo $p['PLUGIN_AUTHOR']; ?>" style="width:100%;"><br>
                        Has FREE: <input type="checkbox" name="projects[<?php echo $slug; ?>][HAS_FREE]" value="1" <?php checked($p['HAS_FREE'], true); ?>>
                        <input type="hidden" name="projects[<?php echo $slug; ?>][PLUGIN_URI]" value="<?php echo $p['PLUGIN_URI']; ?>">
                    </td>
                    <td><button type="button" class="button remove-row" style="color:red;">Delete</button></td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>

        <div style="margin-top:20px;">
            <button type="button" id="add-project" class="button"> + Add New Project / Add-on</button>
            <input type="submit" name="bh_save_projects" class="button button-primary" value="Save Changes to maker-config.php">
        </div>
    </form>
</div>

<script>
jQuery(document).ready(function($) {
    $('#add-project').click(function() {
        var id = 'new_' + Date.now();
        var html = '<tr class="project-row">' +
            '<td><input type="text" name="projects['+id+'][KEY]" placeholder="Unique-Slug"></td>' +
            '<td>ID: <input type="text" name="projects['+id+'][FS_ID]" style="width:100%;"><br>Token: <input type="text" name="projects['+id+'][FS_TOKEN]" style="width:100%;"></td>' +
            '<td><input type="text" name="projects['+id+'][GH_REPO]" style="width:100%;"></td>' +
            '<td>Name: <input type="text" name="projects['+id+'][PLUGIN_NAME]" style="width:100%;"><br>Domain: <input type="text" name="projects['+id+'][PLUGIN_DOMAIN]" style="width:100%;"></td>' +
            '<td>Author: <input type="text" name="projects['+id+'][PLUGIN_AUTHOR]" value="Franz Horvath" style="width:100%;"><br>Has FREE: <input type="checkbox" name="projects['+id+'][HAS_FREE]" value="1"></td>' +
            '<td><button type="button" class="button remove-row" style="color:red;">Delete</button></td>' +
        '</tr>';
        $('#bh-project-list').append(html);
    });

    $(document).on('click', '.remove-row', function() {
        if(confirm('Wirklich löschen?')) { $(this).closest('tr').remove(); }
    });
});
</script>
